# Generated by Django 4.2.11 on 2024-06-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(default='No caption yet', max_length=100),
        ),
    ]
