# Generated by Django 4.2.11 on 2024-06-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_followers_userprofile_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_file',
            field=models.FileField(upload_to='posts/'),
        ),
    ]
