# Generated by Django 4.2.13 on 2024-06-26 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='reply',
        ),
        migrations.CreateModel(
            name='Reply_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=255)),
                ('reply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.comments')),
            ],
        ),
    ]
