# Generated by Django 4.2.13 on 2024-07-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_follower_no_followers_follower_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commment_By',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_model', to='main.post'),
        ),
    ]
