# Generated by Django 4.2.13 on 2024-07-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_post_no_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='follower_of_username',
            field=models.CharField(default='Null', max_length=20),
        ),
    ]
